"""Check source licensing and exact archive notices (Python 3.11+)."""

import argparse
import hashlib
import re
from pathlib import Path

import tomllib

ROOT = Path(__file__).resolve().parents[1]
PROJECT_LICENSE = "PolyForm-Noncommercial-1.0.0"
DISTRIBUTION_LICENSE = PROJECT_LICENSE + " AND MIT AND Apache-2.0"
PINNED_TEXTS = {
    "LICENSES/PolyForm-Noncommercial-1.0.0.md": (
        "c0ea4a896d2c8c394b29f9427589996db826cd501c512279ff0ed3ef48fabbe5"
    ),
    "LICENSES/Apache-2.0.txt": (
        "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"
    ),
    "LICENSES/parasolid-core-MIT.txt": (
        "f6e2a77034e7fd3c2d82b44600b45bf362d6c9b941299d696a7e234525979291"
    ),
    "LICENSES/rust-dependencies.txt": (
        "85326824f4b96f309c68005859b8e0a0878f46a2288fbd285d1d85b55e719cc5"
    ),
}
LICENSE_PATHS = (
    "LICENSE",
    "COMMERCIAL-LICENSE.md",
    "THIRD_PARTY_NOTICES.md",
    *PINNED_TEXTS,
)
REQUIRED_NOTICES = (
    "Required Notice: icadkit is licensed by UnRobotics Inc. "
    "(https://www.un-robotics.com/).",
    "Required Notice: icadkit is offered under PolyForm Noncommercial 1.0.0; "
    "separate commercial licenses are available.",
)


def require(condition, message):
    if not condition:
        raise ValueError(message)


def notice_bundle(root=ROOT):
    result = (
        b"Generated by scripts/check_license.py --write-crate-notices.\n"
        b"Canonical source notices follow; paths refer to the source root.\n"
    )
    for name in LICENSE_PATHS:
        result += b"\n===== " + name.encode() + b" =====\n"
        result += (root / name).read_bytes() + b"\n"
    return result


def check_source(root=ROOT):
    project = tomllib.loads((root / "pyproject.toml").read_text("utf-8"))["project"]
    workspace = tomllib.loads((root / "Cargo.toml").read_text("utf-8"))["workspace"]
    require(project["license"] == DISTRIBUTION_LICENSE, "Python license mismatch")
    require(workspace["package"]["license"] == PROJECT_LICENSE, "Rust license mismatch")
    declared = {
        p.relative_to(root).as_posix()
        for pattern in project["license-files"]
        for p in root.glob(pattern)
        if p.is_file()
    }
    require(declared == set(LICENSE_PATHS), "license-files coverage mismatch")
    for name, digest in PINNED_TEXTS.items():
        require(
            hashlib.sha256((root / name).read_bytes()).hexdigest() == digest,
            f"changed canonical license text: {name}",
        )
    lines = (root / "LICENSE").read_text("utf-8").splitlines()
    require(all(n in lines for n in REQUIRED_NOTICES), "missing Required Notice")
    bundle = notice_bundle(root)
    for member in workspace["members"]:
        package = tomllib.loads((root / member / "Cargo.toml").read_text("utf-8"))[
            "package"
        ]
        require(package["license"] == {"workspace": True}, "crate license override")
        require(
            (root / member / "LICENSE").read_bytes() == bundle, "stale crate notice"
        )
    ledger = (root / "LICENSES/rust-dependencies.txt").read_text("utf-8")
    covered = set(re.findall(r"^=== (\S+) (\S+) \(", ledger, re.MULTILINE))
    lock = tomllib.loads((root / "Cargo.lock").read_text("utf-8"))
    dependencies = {(p["name"], p["version"]) for p in lock["package"] if "source" in p}
    require(
        not dependencies - covered,
        f"missing dependency notices: {dependencies - covered}",
    )


def check_archive_licenses(metadata, read, prefix, root=ROOT):
    require(
        metadata["License-Expression"] == DISTRIBUTION_LICENSE,
        "archive license expression mismatch",
    )
    require(not metadata.get_all("License"), "obsolete License metadata")
    declared = metadata.get_all("License-File", [])
    require(
        len(declared) == len(set(declared)) and set(declared) == set(LICENSE_PATHS),
        "archive License-File coverage mismatch",
    )
    for name in LICENSE_PATHS:
        require(
            read(prefix + name) == (root / name).read_bytes(),
            f"missing or stale archive notice: {prefix + name}",
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-crate-notices", action="store_true")
    args = parser.parse_args()
    if args.write_crate_notices:
        for member in ("icad-core", "icad-python"):
            (ROOT / "crates" / member / "LICENSE").write_bytes(notice_bundle())
    check_source()
    print("Source licensing, canonical texts and dependency notices passed")
